<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom Styling -->
    <link rel="stylesheet" href="../css/style.css">

    <!-- Admin Styling -->
    <link rel="stylesheet" href="../css/admin.css">

    <title> Add Post</title>
</head>

<body>
    <?php include 'navbar.phtml'; ?>

    <!-- Admin Page Wrapper -->
    <div class="admin-container">


        <!-- // Left Sidebar -->


        <!-- Admin Content -->


        <div class="container">

            <h2 class="page-title"> Gestions des articles</h2>

            <?php include 'formsErrors.php'; ?>
            <form action="Location:index.php?action=addArticle" enctype="multipart/form-data" method="post">

                <div>
                    <label>Title</label>
                    <input type="text" name="title" class="text-input">
                </div>

                <div>
                    <label>Title</label>
                    <input type="text" name="title" class="text-input">
               
                <select class="form-select" aria-label="Default select example">
                    <option selected>Open this select menu</option>
                    <option value="">One</option>
                   
                   
                </select>
                </div>
                <div>
                    <label>Contenu</label>
                    <textarea cols="130" , rows="10" name="content" id="body"></textarea>
                </div>
                <div>
                    <label>Image</label>
                    <input type="file" name="image" class="text-input">
                </div>

                <div>
                    <button type="submit" name="add-post" class="btn btn-big">Add Post</button>
                </div>
            </form>

        </div>

    </div>
    <!-- // Admin Content -->

    </div>
    <!-- // Page Wrapper -->


</body>