
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <title>Document</title>
</head>

<body>
  <div id="form">
  <div class="container mt-1">
    <form method="post">
      <div class="form-group">
        <label for="name">Prenom</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
          placeholder="Enter a name" name="prenom">

      </div>
      <div class="form-group">
        <label for="name">Email</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
          placeholder="Enter a email" name="email">

      </div>
      <div class="form-group">
        <label for="role">Rôle</label>
        <select  class="form-select" aria-label="Default select example"
          id="exampleInputPassword1" placeholder="admin or user" name='role'>
          <option selected>Open this select menu</option>
          <option value="admin">admin</option>
          <option value="user">user</option>
        
        </select>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name='password'>
      </div>

    

      <button type="submit" class="btn btn-primary" name="submit">Submit</button>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"></script>
</body>


</html>

<style>
