

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</head>
<body>
<h1 class="text-center" style="background-color:red">ADMIN CRUD</h1>
    <div class="container">
        <div class="sucess">
            <h1 class="mt-3 ">Bienvenue !<?php echo $_SESSION['user']['prenom']?> <a class="btn btn-danger"
                    href="index.php?action=logout" style="float:right;padding:11px">log out</a></h1>

            <strong>
                <p class="mt-3" style="color:green">C'EST VOTRE ESPACE ADMIN.</p>

            </strong>
            <a class="btn btn-primary" href="index.php?action=Admincategorie">list des categorie</a>
            <a class="btn btn-primary" href="#"> list des posts</a>
            <div class ="container" style="border:solid" >
            <table class="table caption-top">
                <h1 class="text-center">List of users</h1>
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Prenom</th>
                        <th scope="col">Email</th>
                        <th scope="col">Role</th>
                        <th scope="col">Action</th>
                    </tr>
                    <?php
                    foreach ($users as $user) {
                        ?>
                        <tr>
                            <td><?= $user['id']?></td>
                            <td><?= $user['prenom']?></td> 
                            <td><?= $user['email']?></td>
                            <td><?= $user['role']?></td>
                           
                                 
                            <td><a class="btn btn-success" href="./../crud/modifiercrud.php?id=<?= $id['id'] ?>">Modifier</a><a class="btn btn-danger" href="index.php?action=ove">Supprimer</a></td>
                        </tr>
                        </th>
                    <?php
                    }
                    ?>
                    </tbody>
                    </tbody>
            </table>
            <a class="btn btn-primary" href="index.php?action=adduser">Ajouter un user</a>
        </div>




</body>
</html>
