<?php
session_start();
if (!isset($_SESSION['user'])) {
    header('Location:../connect.php');
}


require_once('../refactoring.php');

$perPage= 5 ;
$nombreTotal= pagination();

$noPage= 1;
$pages = ceil($nombreTotal/$perPage);
if (isset($_GET['page'])) {
    $noPage = $_GET['page'];
    
  }
$posts= selectAll($noPage,$perPage);

?>

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Custom Styling -->
        <link rel="stylesheet" href="../css/style.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <!-- Admin Styling -->
        <link rel="stylesheet" href="../css/admin.css">
 
        <title>Section Admin - Gestions des articles</title>
    </head>

    <body>
           

        <!-- Admin Page Wrapper -->
        <div class="admin-container">

            <!-- Admin Content -->
            <div class="admin-content">
                <div class="button-group">
                    <a href="create.php" class="btn btn-big">Ajouter un article</a>
                    
                <div class="container">
                    <h2 class="page-title">Gestion des articles</h2>
                    <table>
                        <thead>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th colspan="3">Action</th>
                        </thead>
                        <tbody>
                                   <?php foreach( $posts as $key=>$post):?>
                                <tr>
                                    <td><?= $key +1; ?></td>
                                    <td><?= $post['title']?></td>
                                    <td><?= $post['userid']?></td>
                                    <td><a href="edit.php?id=<?php echo $post['id']?>" class="btn btn-primary">Edit</a></td>
                                    <td><a href="edit.php?delete_id=<?php echo $post['id']?>" class="btn btn-danger">Delete</a></td>  
                                </tr>
                                <?php endforeach;?>
                               
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
        <div class="pagination">
      <?php
        for ($i=1; $i <= $pages ; $i++) { ?>
          <a class="page <?= ($noPage == $i)?'active':'' ?>" href="index.php?page=<?= $i ?>"><?= $i ?></a>
      <?php }
      ?>
    </div>
   
    </body>

</html>