<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</head>
<body>
<h1 class="text-center" style="background-color:red">ADMIN CRUD</h1>
       
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<title>crud</title>
</head>
<body>
    <div class="container">
        <div class="sucess">
            <h1 class="mt-3 ">Bienvenue <?php echo $_SESSION['user']['name']; ?>! <a class="btn btn-danger"
                    href="./../deconnection.php" style="float:right;padding:11px">log out</a></h1>
            <strong>
                <p class="mt-3" style="color:green">C'EST VOTRE ESPACE ADMIN.</p>
            </strong>
            <table class="table caption-top">
                <h1 class="text-center">List of users</h1>
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Role</th>
                        <th scope="col">Bloqués</th>
                        <th scope="col">Action</th>
                    </tr>
                    <?php
                    foreach ($result as $id) {
                        ?>
                        <tr>
                            <td></td>
                            <td </td>
                            <td></td>
                            <td></td>
                            <td> <?php if($id['Blocked']== 1){    
                                echo "Blocked";
                            } else{
                                
                                echo "Unblocked";}
                                 ?>
                                 </td>
                            <td><a class="btn btn-success" href="./../crud/modifiercrud.php?id=<?= $id['id'] ?>">Modifier</a><a class="btn btn-danger" href="./../crud/deletecrud.php?id=<?= $id['id'] ?>">Supprimer</a></td>
                        </tr>
                        </th>
                    <?php
                    }
                    ?>
                    </tbody>
                    </tbody>
            </table>
            <a class="btn btn-primary" href="./../crud/ajoutercrud.php">Ajouter un user</a>
  

</body>
</html>
