<?php include 'navbar.phtml'; ?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Custom Styling -->
  <link rel="stylesheet" href="public/css/style.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <title>Article </title>
</head>

<body>
  <!-- Page header -->
  <!-- Page Wrapper -->
  <div class="page-container">
    <!-- Content -->
    <div class="container">
      <!-- Main Content Wrapper -->
      <div class="">
        <div class="main-content single">
          <h1 class="post-title">
            <?= $posts['title'] ?>
          </h1>
          <div class="post-image">
            <img src="<?php echo './public/image/' . $posts['image'] ?>" alt="">
          </div>
          </br>
          <div class="post-content">
            <?= $posts['content'] ?></br>
            <strong> Auteur:
              <?= $posts['prenom']; ?> </br> publié le
              <?= $posts['created_at'] ?> dans la catgeorie
              <?= $posts['name']; ?>
            </strong>
          </div>
        </div>
      

      <form method="post"action="index.php?action=commenter&id=<? $posts[">
        <div class="form-group">
          <textarea class="form-control" name="content" rows="4" placeholder="Ecriver votre commentaire.. "></textarea>
        </div>
        <div class ="form-group">
          <button class="btn btn-primary" type="submit" name="ajout-commenaire">Commenter</button>
        </div>
      </form>
    </div>


      <div style="background:white; box-shadow: 0 5px 15px rgba(0,0,0.15); padding:5px 10px; border-radius:10px;margin-top:20px;">
        <h1>Les Commentaires</h1>
        <?php foreach ($coms as $comment) {
          ?>
          <div style="background: #eee; margin-top:20px;padding:5px 10px;border-radius:10px">
            <div style="font-weight:bold">
              <?= "De " . $comment['prenom'] . "" ?>
            </div>
            <?= htmlspecialchars($comment['comment']) ?>
            <div style="text-align:right;font-size:12px;color:#665">
            <?= date('d F ,Y', strtotime($comment['created_at'])) ?>
            </div>
          </div>
          <?php
        }
        ?>

      </div>
    </div>


   

 


</body>

</html>