<?php include 'navbar.phtml'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Custom Styling -->
  <link rel="stylesheet" href="public/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <title>Article </title>
</head>
<body>
    <!-- Page header -->
  <!-- Page Wrapper -->
  <div class="page-container">
    <!-- Content -->
    <div class="container">
      <!-- Main Content Wrapper -->
      <div class="">
        <div class="main-content single">
          <h1 class="post-title"><?= $posts['title']?></h1>
          <div class="post-image">
              <img src="<?php echo './public/image/'.$posts['image']?>"alt="" >
          </div>
        </br>
          <div class="post-content">
            <?= $posts['content']?></br>
            <strong> Auteur: <?= $posts['prenom']; ?> </br> publié le <?= $posts['created_at']?> dans la catgeorie <?= $posts['name']; ?> </strong>
          </div>
        </div>
         <h1>Les commentaires</h1>
        <div class="comments">
            <?php foreach($coms as $comment ):?>
              <div style="background:white; box-shadow: 0 5px;
            <div class="comment">
              <h3 class="auteur">Est ecrit par <?= $comment['prenom'];?></h3>
              <p class="contenu" ><?= $comment['comment'];?><br>
              <i class="far fa-calendar"> <?= date('d F ,Y',strtotime($comment['created_at']));?></i>
              <a class="sup" href="">Supprimer</a>
              </p>
              <br>
            </div>
            <?php endforeach ; ?>
        </div>
        <br>
        <form action=" <?= $id?>"  method="post">
        
            <label>Body</label>
            <textarea name="comment" id="body" cols="130" rows="15"></textarea>
          </div><br>
          <div>
              <button type="submit" name="add-comment" class="btn btn-primary">Commentez</button>
          </div>
        </form>
        
      </div>
    </div>
  </div> 
      <!-- // Main Content

     


</body>

</html>