
 




<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Custom Styling -->
        <link rel="stylesheet" href="../css/style.css">

        <!-- Admin Styling -->
        <link rel="stylesheet" href="../css/admin.css">

        <title>Admin Section - Edit Post</title>
    </head>

    <body>
       
        <div class="admin-container">
                <div class="container">

                    <h2 class="page-title">Modifier un article </h2>
                  
                    <form action="edit.php" method="post" enctype="multipart/form-data">
                      
                          
                        <div>
                            <label>Title</label>
                            <input type="text" name="title" value="<?= $title; ?>"   class="text-input">
                        </div>
                        <div>
                            <label>Contenu</label>
                            <textarea cols="130", rows="10" name="content" id="body">
                            <?= $content; ?>     
                            </textarea>
                       
                            <button type="submit" name="update-post" class="btn btn-big">Mettre à jours</button>
                        </div>
                    </form>

                </div>

            </div>
            <!-- // Admin Content -->
