<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>
    <script type="text/javascript" src="script.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="css/style.css">
</head>
 
 
 



<section class="articles">
    
     <div class="article">
      <div class="left">
        <img src="https://cdn.pixabay.com/photo/2016/11/18/19/01/paris-1836415_1280.jpg" alt="">
      </div>
      <div class="right">
        <p class="date">Juillet, 24, 2020</p>
        <h1>Paris - La ville des lumières, pourquoi ?</h1>
        <p class="description">
        Paris Ville Lumière… Si le surnom de la capitale est bien connu, son origine l’est moins. Et il faut remonter bien loin, à l’heure où l’électricité n’était pas encore d’actualité, pour en trouver la signification. Petit retour en arrière sur cette anecdote !

Si aujourd’hui Paris est loin d’être la métropole la plus éclairée, cela n’a pas toujours été le cas. Les origines supposées du surnom “Ville Lumière” pour notre belle capitale sont multiples, mais on doit sans aucun doute ce sobriquet aux étrangers et provinciaux venus faire une halte ici.


        </p>
        <p class="auteur">Julie Lablonde</p>
      </div>
    </div> 
    
    
    <div class="article">
      <div class="left">
        <img src="public/image/870814.jpg"alt="">
      </div>
      <div class="right">
        <p class="date">, 24, 2021</p>
        <h1>Interview - Une ville nocture est elle si belle ?</h1>
        <p class="description">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad cupiditate repellendus dolor necessitatibus. Modi, quos! Explicabo voluptates vero ullam quis ipsum impedit illum numquam cum quaerat animi? Ad, fugiat neque.</p>
        <p class="auteur">Julie Lablonde</p>
      </div>
    </div>
    
    <div class="article">
      <div class="left">
        <img src="https://cdn.pixabay.com/photo/2017/01/09/16/15/calanque-1966920_1280.jpg" alt="">
      </div>
      <div class="right">
        <p class="date">Juillet, 24, 2020</p>
        <h1>Les calanques, une belle destination touristique</h1>
        <p class="description">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad cupiditate repellendus dolor necessitatibus. Modi, quos! Explicabo voluptates vero ullam quis ipsum impedit illum numquam cum quaerat animi? Ad, fugiat neque.</p>
        <p class="auteur">Julie Lablonde</p>
      </div>
    </div>
  </section>
  
  
</body>
</html>
<style>

.articles{
  margin-top: 30px;
}
.articles .article{
  display: flex;
  flex-wrap:wrap;
  margin-bottom: 30px;
}
.articles .article .left img{
  height: 300px;
  width: 500px;
  margin: 10px;
}
.articles .article .right {
  margin-left: 40px;
  max-width: 50%;
}
.articles .article .right p.date{
  color: #7f7e7e;
}
.articles .article .right p.description{
  color: #2d2d2d;
}

body{
  margin:0px;
  font-family: 'Noto Sans JP', sans-serif;
}

</style>