
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Custom Styling -->
        <link rel="stylesheet" href="../css/style.css">

<header>
    <div class="logo">
        <h1 class="logo-text"><span>READ</span>BLog</h1>
    </div>
    <ul class="nav">
      

            <li><a href="index.php?action='Home'">Home</a></li>
            

            <li><a href="inscription.php">S'inscrire</a></li>
            <li><a href="connect.php">Se connecter</a></li>
        
          
            
            <li><a href="">Articles</a></li>

           
       
    </ul>
    </
       

</header>