<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>
    <script type="text/javascript" src="script.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="public/css/style.css">
</head>
 
 
<header>
    <div class="logo">
        <h1 class="logo-text"><span>READ</span>BLog</h1>

    </div>
    <ul class="nav">
    
    <?php
            if (!isset($_SESSION['user'])) {
              ?>

            <li><a href="index.php?action=Home" style="color:white">Home</a></li>
            <li><a href="index.php?action=Register style="color:white">S'inscrire</a></li>
            <li><a href="index.php?action=Connect"style="color:white>Se connecter</a></li>
            
            <?php
           }
            else{
                ?>
                 <h1>BIENVENUE <?php echo $_SESSION['user']['prenom']?></h1>
                 <li><a href="index.php?action=display">Articles</a></li>
  
                <li><a href="index.php?action=logout">Deconnection </a></li>
                <?php
            }
            
            ?>
        

           
       
    </ul>  
</header>