<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>
    <script type="text/javascript" src="script.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="public/css/style.css">
</head>
 
 
<header>
    <div class="logo">
        <h1 class="logo-text"><span>READ</span>BLog</h1>

    </div>
    <ul class="nav">
    
    <?php
            if (!isset($_SESSION['user'])) {
              ?>

            <li><a href="index.php?action=Home">Home</a></li>
            <li><a href="index.php?action=Register">S'inscrire</a></li>
            <li><a href="index.php?action=Connect">Se connecter</a></li>
            <li><a href="index.php?action=display">Articles</a></li>
            <?php
           }
            else{
                ?>

                <li><a href="index.php?action=logout">Deconnection </a></li>
                <li class="nav-item">
                                <a class="nav-link" ><?php echo $_SESSION['user']</a>
                            </li>
                <?php
            }
            
            ?>
        

           
       
    </ul>  
</header>